# Site settings
title: Peanut Butter Jelly Things
email: keenan.johnson@gmail.com
description: 
baseurl: "/pbj/" # the subpath of your site, e.g. /blog/
url: "http://keenanjohnson.github.io" # the base hostname & protocol for your site
twitter_username: keenanjohnson
github_username:  keenanjohnson

# Build settings
markdown: kramdown
